- name: Provision EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch EC2 instance
      ec2:
        key_name: my-key
        instance_type: t2.micro
        image: ami-12345678
        region: us-east-1
        count: 1
        vpc_subnet_id: subnet-12345678
        group: my-security-group
        wait: yes
      register: ec2

    - name: Add the new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        ansible_ssh_user: ec2-user
        ansible_ssh_private_key_file: /path/to/key.pem
        ansible_python_interpreter: /usr/bin/python3
      with_items: "{{ ec2.instances }}"
