- name: Deploy Docker containers
  hosts: docker_servers
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      command: pip install docker-compose

    - name: Deploy containers using Docker Compose
      command: docker-compose -f /path/to/docker-compose.yml up -d
