---
- name: Install MySQL
  hosts: mysql_servers  # Replace with the group of servers where you want to install MySQL
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update APT package cache (for Ubuntu/Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present
      when: ansible_os_family == "Debian"

    - name: Start the MySQL service
      service:
        name: mysql
        state: started

    - name: Enable MySQL service on system boot
      service:
        name: mysql
        enabled: yes

    - name: Secure MySQL installation (set root password)
      mysql_user:
        name: admin
        password: password
      when: ansible_os_family == "Debian"


